image: ituverava.coids.inpe.br/library/python:3.10-bookworm

pages:
  stage: deploy
  tags:
    - build
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install -r requirements.txt
  script:
    - cd docs && make html
  after_script:
    - mv docs/_build/html/ ./public/
  artifacts:
    paths:
    - public
  only:
  - master
